package com.fastmask.ui.theme

import androidx.compose.ui.graphics.Color

// Fastmail Brand Colors
val FastmailBlue = Color(0xFF0066CC)
val FastmailBlueLight = Color(0xFF4D94DB)
val FastmailBlueDark = Color(0xFF004C99)

// M3 Light Theme Colors
val md_theme_light_primary = Color(0xFF0061A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E3F7)
val md_theme_light_onSecondaryContainer = Color(0xFF101C2B)
val md_theme_light_tertiary = Color(0xFF6B5778)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF2DAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF251431)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_outlineVariant = Color(0xFFC3C7CF)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9ECAFF)
val md_theme_light_surfaceTint = Color(0xFF0061A4)
val md_theme_light_scrim = Color(0xFF000000)

// M3 Surface Containers (Light)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF7F6FA)
val md_theme_light_surfaceContainer = Color(0xFFF1F0F4)
val md_theme_light_surfaceContainerHigh = Color(0xFFEBEBEF)
val md_theme_light_surfaceContainerHighest = Color(0xFFE6E5E9)

// M3 Dark Theme Colors
val md_theme_dark_primary = Color(0xFF9ECAFF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497D)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFFBBC7DB)
val md_theme_dark_onSecondary = Color(0xFF253140)
val md_theme_dark_secondaryContainer = Color(0xFF3B4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E3F7)
val md_theme_dark_tertiary = Color(0xFFD6BEE4)
val md_theme_dark_onTertiary = Color(0xFF3B2948)
val md_theme_dark_tertiaryContainer = Color(0xFF523F5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFF2DAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0061A4)
val md_theme_dark_surfaceTint = Color(0xFF9ECAFF)
val md_theme_dark_scrim = Color(0xFF000000)

// M3 Surface Containers (Dark)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0F1113)
val md_theme_dark_surfaceContainerLow = Color(0xFF1A1C1E)
val md_theme_dark_surfaceContainer = Color(0xFF1E2022)
val md_theme_dark_surfaceContainerHigh = Color(0xFF282A2D)
val md_theme_dark_surfaceContainerHighest = Color(0xFF333537)

// Semantic Status Colors - Light Theme (Tonal Containers)
val StatusEnabledContainerLight = Color(0xFFD4F5D0)
val StatusEnabledContentLight = Color(0xFF0D5F0D)
val StatusDisabledContainerLight = Color(0xFFE0E0E0)
val StatusDisabledContentLight = Color(0xFF5C5C5C)
val StatusDeletedContainerLight = Color(0xFFFFDAD6)
val StatusDeletedContentLight = Color(0xFFBA1A1A)
val StatusPendingContainerLight = Color(0xFFFFE0B2)
val StatusPendingContentLight = Color(0xFFB36B00)

// Semantic Status Colors - Dark Theme (Tonal Containers)
val StatusEnabledContainerDark = Color(0xFF1E4D1E)
val StatusEnabledContentDark = Color(0xFF90EE90)
val StatusDisabledContainerDark = Color(0xFF3D3D3D)
val StatusDisabledContentDark = Color(0xFFB0B0B0)
val StatusDeletedContainerDark = Color(0xFF93000A)
val StatusDeletedContentDark = Color(0xFFFFB4AB)
val StatusPendingContainerDark = Color(0xFF7A4700)
val StatusPendingContentDark = Color(0xFFFFCC80)
